modules:
  - name: welcome
  - name: partition
  - name: fstab
  - name: unpackfs
  - name: machineid
  - name: users
  - name: displaymanager
  - name: packages
  - name: grubcfg
  - name: bootloader
  - name: shellprocess
  - name: finished
