modules-search: [ local ]
instances:
- id: partition
  module: partition
  config: partition.conf
- id: fstab
  module: fstab
- id: unpackfs
  module: unpackfs
  config: unpackfs.conf
- id: machineid
  module: machineid
- id: users
  module: users
- id: displaymanager
  module: displaymanager
  config: displaymanager.conf
- id: packages
  module: packages
- id: grubcfg
  module: grubcfg
- id: bootloader
  module: bootloader
- id: shellprocess_final
  module: shellprocess
  config: shellprocess_final.conf
- id: finished
  module: finished
